---

before:
  hooks:
    - make build
    - make man
    - make completion

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    files:
      - LICENSE
      - README.md
      - completions/*
      - man/*

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "^ci:"
      - "typo"

aurs:
  - name: "devc-bin"
    homepage: "https://github.con/nikaro/devc"
    description: "CLI tool to manage your devcontainers."
    maintainers:
      - "Nicolas Karolak <nicolas at karolak dot fr>"
    license: "GPLv3"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/devc-bin.git"
    package: |-
      install -Dm755 "./devc" "${pkgdir}/usr/bin/devc"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/devc/LICENSE"
      install -Dm644 "./man/devc*.1" "${pkgdir}/usr/share/man/man1/"
      install -Dm644 "./completions/devc" "${pkgdir}/usr/share/bash-completion/completions/"
      install -Dm644 "./completions/devc.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/_devc" "${pkgdir}/usr/share/zsh/site-functions/"

brews:
  - name: "devc"
    homepage: "https://github.con/nikaro/devc"
    description: "CLI tool to manage your devcontainers"
    license: "GPL-3.0-or-later"
    tap:
      owner: "nikaro"
      name: "homebrew-tap"
      token: "{{ .Env.GH_PAT }}"
    folder: "Formula"
    install: |-
      bin.install "devc"
      man1.install Dir["man/*"]
      bash_completion.install "completions/devc"
      fish_completion.install "completions/devc.fish"
      zsh_completion.install "completions/_devc"
    test: |-
      system "#{bin}/devc", "init"

nfpms:
  - package_name: "devc"
    homepage: "https://github.con/nikaro/devc"
    description: "CLI tool to manage your devcontainers."
    maintainer: "Nicolas Karolak <nicolas@karolak.fr>"
    license: "GPLv3"
    formats:
      - "apk"
      - "deb"
      - "rpm"
    contents:
      - src: "LICENSE"
        dst: "/usr/share/licenses/devc/LICENSE"
      - src: "man/devc*.1"
        dst: "/usr/share/man/man1/"
      - src: "completions/devc"
        dst: "/usr/share/bash-completions/completions/"
      - src: "completions/devc.fish"
        dst: "/usr/share/fish/vendor_completions.d/"
      - src: "completions/_devc"
        dst: "/usr/share/zsh/site-functions/"
