---

name: Feature Request
description: Ask for new feature or request
labels: ["enhancement"]
assignees:
  - nikaro
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve this software!
  - type: textarea
    id: request
    attributes:
      label: Request
      description: Describe the feature you want
      placeholder: I want THIS feature because i'm want to do THAT.
    validations:
      required: true
